// <auto-generated />
namespace E_Pay_Web_API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class finaliseFinancialInstitutionAdminEmails : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(finaliseFinancialInstitutionAdminEmails));
        
        string IMigrationMetadata.Id
        {
            get { return "201707171822086_finaliseFinancialInstitutionAdminEmails"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
