// <auto-generated />
namespace E_Pay_Web_API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddAssociatedAccountsCOBSecurityReviewsJoinTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddAssociatedAccountsCOBSecurityReviewsJoinTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201711071002091_AddAssociatedAccountsCOBSecurityReviewsJoinTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
